receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: "http://jaeger:14250"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
